/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "outline-variant": "#e1bfb5",
              "primary-fixed-dim": "#ffb59e",
              "inverse-primary": "#ffb59e",
              "on-primary": "#ffffff",
              "tertiary-fixed-dim": "#58d6f3",
              "tertiary-container": "#00a8c4",
              "inverse-surface": "#2f3034",
              "on-secondary": "#ffffff",
              "primary-container": "#ff6a39",
              "on-tertiary-fixed": "#001f26",
              "on-surface": "#1a1c1f",
              "inverse-on-surface": "#f0f0f4",
              "surface-container": "#ededf2",
              "surface-container-high": "#e8e8ec",
              "border-light": "#E5E7EB",
              "surface-dim": "#d9dade",
              "card-fill-sage": "#E8F3F1",
              "surface-bright": "#f9f9fd",
              "tertiary": "#00687a",
              "tertiary-fixed": "#acedff",
              "on-primary-container": "#5f1700",
              "secondary-fixed": "#87f6dc",
              "on-tertiary": "#ffffff",
              "text-muted": "#6B7280",
              "surface-tint": "#ae3200",
              "surface": "#f9f9fd",
              "outline": "#8d7168",
              "on-secondary-fixed-variant": "#005143",
              "surface-container-low": "#f3f3f7",
              "card-fill-cream": "#F9F8F3",
              "secondary": "#006b5a",
              "on-primary-fixed-variant": "#852400",
              "on-error-container": "#93000a",
              "on-secondary-fixed": "#00201a",
              "error": "#ba1a1a",
              "background-surface": "#FFFFFF",
              "secondary-container": "#84f3d9",
              "secondary-fixed-dim": "#69d9c0",
              "on-tertiary-fixed-variant": "#004e5c",
              "on-tertiary-container": "#003742",
              "dark-section-bg": "#0E1512",
              "on-primary-fixed": "#3a0b00",
              "primary-fixed": "#ffdbd0",
              "background": "#f9f9fd",
              "surface-variant": "#e2e2e6",
              "on-background": "#1a1c1f",
              "surface-container-lowest": "#ffffff",
              "on-surface-variant": "#59413a",
              "surface-container-highest": "#e2e2e6",
              "primary": "#ae3200",
              "on-secondary-container": "#00705e",
              "on-error": "#ffffff",
              "error-container": "#ffdad6"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "stack-md": "1rem",
              "stack-lg": "2.5rem",
              "max-width": "1280px",
              "stack-sm": "0.5rem",
              "gutter": "32px",
              "section-v-padding": "100px"
      },
      "fontFamily": {
              "body-md": ["Hanken Grotesk", "sans-serif"],
              "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
              "label-caps": ["Hanken Grotesk", "sans-serif"],
              "display-lg": ["Hanken Grotesk", "sans-serif"],
              "headline-md": ["Hanken Grotesk", "sans-serif"],
              "body-lg": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
              "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
              "display-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700"}],
              "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
              "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700"}],
              "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
